---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:us-west-2:273354636904:generatedTemplate/65ffc8ce-a3e8-407e-a279-2211d185d4a5"
Resources:
  # S3 Build Artifacts Bucket
  S3Bucket00nextworkbuildartifactsjoeyacosta008A3dz:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "nextwork-build-artifacts-joeyacosta"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
  CodeArtifactRepository00repositorynextworknextworkpackages00CkiEn:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      Upstreams:
      - Fn::GetAtt:
        - "CodeArtifactRepository00repositorynextworkmavencentralstore002Oug6"
        - "Name"
      RepositoryName: "nextwork-packages"
      Description: "Packages for the NextWork web app."
      DomainName:
        Fn::GetAtt:
        - "CodeArtifactDomain00domainnextwork00wj8zP"
        - "Name"
  #IAM Base Policy for CodeBuild
  IAMManagedPolicy00policyserviceroleCodeBuildBasePolicynextworkwebbuilduswest2006ypn2:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00WYH0s"
    Properties:
      ManagedPolicyName: "CodeBuildBasePolicy-nextwork-web-build-us-west-2"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:logs:us-west-2:273354636904:log-group:/aws/codebuild/nextwork-web-build"
          - "arn:aws:logs:us-west-2:273354636904:log-group:/aws/codebuild/nextwork-web-build:*"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Effect: "Allow"
        - Resource:
          - "arn:aws:s3:::codepipeline-us-west-2-*"
          Action:
          - "s3:PutObject"
          - "s3:GetObject"
          - "s3:GetObjectVersion"
          - "s3:GetBucketAcl"
          - "s3:GetBucketLocation"
          Effect: "Allow"
        - Resource:
          - "arn:aws:s3:::nextwork-build-artifacts-joeyacosta"
          - "arn:aws:s3:::nextwork-build-artifacts-joeyacosta/*"
          Action:
          - "s3:PutObject"
          - "s3:GetBucketAcl"
          - "s3:GetBucketLocation"
          Effect: "Allow"
        - Resource:
          - "arn:aws:codebuild:us-west-2:273354636904:report-group/nextwork-web-build-*"
          Action:
          - "codebuild:CreateReportGroup"
          - "codebuild:CreateReport"
          - "codebuild:UpdateReport"
          - "codebuild:BatchPutTestCases"
          - "codebuild:BatchPutCodeCoverages"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []
  # IAM Policy for CodeArtifact
  IAMManagedPolicy00policycodeartifactnextworkconsumerpolicy00FKLjR:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00WYH0s"
    Properties:
      ManagedPolicyName: "codeartifact-nextwork-consumer-policy"
      Path: "/"
      Description: "Provides permissions to read from CodeArtifact."
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "*"
          Action:
          - "codeartifact:GetAuthorizationToken"
          - "codeartifact:GetRepositoryEndpoint"
          - "codeartifact:ReadFromRepository"
          Effect: "Allow"
        - Condition:
            StringEquals:
              sts:AWSServiceName: "codeartifact.amazonaws.com"
          Resource: "*"
          Action: "sts:GetServiceBearerToken"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []
  # CodeArtifact Upstream Repository
  CodeArtifactRepository00repositorynextworkmavencentralstore002Oug6:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      RepositoryName: "maven-central-store"
      Description: "Provides Maven artifacts from Maven Central Repository."
      ExternalConnections:
      - "public:maven-central"
      DomainName:
        Fn::GetAtt:
        - "CodeArtifactDomain00domainnextwork00wj8zP"
        - "Name"
  # IAM Role for CodeBuild
  IAMRole00codebuildnextworkwebbuildservicerole00WYH0s:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/service-role/"
      MaxSessionDuration: 3600
      RoleName: "codebuild-nextwork-web-build-service-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"
      Policies:
        - PolicyName: "CodeBuildSecretsManagerPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: "arn:aws:secretsmanager:us-west-2:273354636904:secret:GitHubToken-iI2sy3"
  IAMManagedPolicy00policyserviceroleCodeBuildCodeConnectionsSourceCredentialsPolicynextworkwebbuilduswest200oieP0:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00WYH0s"
    Properties:
      ManagedPolicyName: "CodeBuildCodeConnectionsSourceCredentialsPolicy-nextwork-web-build-us-west-2"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:codestar-connections:us-west-2:273354636904:connection/fc948b5f-b4c9-465e-b163-67c54fa676af"
          - "arn:aws:codeconnections:us-west-2:273354636904:connection/fc948b5f-b4c9-465e-b163-67c54fa676af"
          Action:
          - "codestar-connections:GetConnectionToken"
          - "codestar-connections:GetConnection"
          - "codeconnections:GetConnectionToken"
          - "codeconnections:GetConnection"
          - "codeconnections:UseConnection"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []
  # CodeArtifact Domain
  CodeArtifactDomain00domainnextwork00wj8zP:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Domain"
    DeletionPolicy: "Delete"
    Properties:
      DomainName: "nextwork"
  # IAM Policy for CodeBuild CloudWatch Logs
  IAMManagedPolicy00policyserviceroleCodeBuildCloudWatchLogsPolicynextworkwebbuilduswest200g29sl:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00WYH0s"
    Properties:
      ManagedPolicyName: "CodeBuildCloudWatchLogsPolicy-nextwork-web-build-us-west-2"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:logs:us-west-2:273354636904:log-group:nextwork-build-logs"
          - "arn:aws:logs:us-west-2:273354636904:log-group:nextwork-build-logs:*"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []
  # CodeBuild Project
  CodeBuildProject:
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00WYH0s"
    Type: AWS::CodeBuild::Project
    Properties:
      Name: nextwork-web-build
      Description: Build project for NextWork web application
      Source:
        Type: GITHUB
        Location: https://github.com/joeycloudio/nextwork-devops-webapp.git  # Replace with your actual GitHub repo URL
        BuildSpec: buildspec.yml
        Auth:
          Type: OAUTH
          Resource: arn:aws:secretsmanager:us-west-2:273354636904:secret:GitHubToken-iI2sy3  # Replace with your GitHub token secret ARN from Secrets Manager
      Artifacts:
        Type: S3
        Name: nextwork-web-build.zip
        Packaging: ZIP
        Location: !Ref S3Bucket00nextworkbuildartifactsjoeyacosta008A3dz
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:corretto8
      ServiceRole: !GetAtt IAMRole00codebuildnextworkwebbuildservicerole00WYH0s.Arn
      LogsConfig:
        CloudWatchLogs:
          GroupName: nextwork-build-logs
          Status: ENABLED
          StreamName: webapp